### ISSUE TITLE
拦截器是否可以根据业务的上下文进行路由

### ISSUE THREAD

**Issue by Cloud33** [yuzd/Autofac.Annotation#1]
拦截器是否可以根据业务的上下文进行路由？
业务场景，asp.net mvc 有一些虚方法，在执行操作时，有业务代码就会在控制器中实现这些虚方法，但是这个依赖与 mvc管道，想用Autofac.Annotation代替，所以请问有什么方法摆脱这种方式，想像博主这样，使用AOP标签这种方式，如果有业务需要，就打上标签就行了。
请博主多多指教，谢谢。

**Comment by yuzd** [comment]
你是说mvc的filter吗？或者举个例子告诉我一个虚方法名称

**Comment by Cloud33** [comment]
是这样的，因为是做表单，所有的表单肯定会有一个提交表单数据的API，所以，目前的做法是， 定义一个基类，比如叫FormController：
![image](https://user-images.githubusercontent.com/8787198/66032755-8becec00-e538-11e9-84e8-96d7c8a6093d.png)
它里面有一个保存API，然后也会在基类中定义前后事件，这些方法被声明为virtual。
然后在表单的Controller中，会这样去写自己的业务逻辑。
![image](https://user-images.githubusercontent.com/8787198/66032934-e38b5780-e538-11e9-8393-8f46de45e9d8.png)
可能还有些其它的API，但是都是这样的情况。

**Comment by yuzd** [comment]
你这种的话 可以
1.  使用一个Arround拦截器 
2. 或者用一个前置和后置拦截器

但是如果不同的业务 你的OnformSaveBefore 或者 OnFormSaveAfter 处理的内容不一样的话，得按照业务来搞对应的拦截器（我觉得这个还不如你现在来的方便）
因为如果让你每个业务都搞一个对应的业务拦截器的话，代码就不能复用了，岂不是违背了AOP的设计初衷了，你觉得呢？

**Comment by Cloud33** [comment]
是的，是需要按照业务来搞对应的拦截器。
这就回到我最开始的问题，在Arround拦截器里面，我是否可以动态根据业务数据（例如：表单类型）调用业务自己的拦截器；**这些拦截器上下文是一样的。**

**Comment by yuzd** [comment]
一个方法可以打多个拦截器标签，
比如 一个是通用的拦截器是专门来解析
另外一个是针对有业务的拦截器
上下文都是通用的。每个拦截器都是可以获取请求参数并且拦截器里面 可以修改或者重新赋值。


你可以用我的单元测试模拟一下，
https://github.com/yuzd/Autofac.Annotation/blob/master/test/test3/UnitTest3.cs#L137

**Comment by yuzd** [comment]
我刚把拦截器的功能完善了，PointCut拦截器支持多个累加可以 netcore 的 middleware 一样。
参考
https://github.com/yuzd/Autofac.Annotation/blob/679c2bd4064d51d886ae96d3208c4525f70a5a44/test/test3/Test3Models.cs#L297-L354
