### ISSUE TITLE
[Component]如果关闭自动注册父类的问题

### ISSUE THREAD

**Issue by yus1977** [yuzd/Autofac.Annotation#11]
[Component]会把父类自动注册，即使父类是虚类。如果关闭它，只自动注册接口就行，父类（尤其是虚类）就不用自动注册了。

**Comment by yuzd** [comment]
abstract的被自动注册的问题吗？
可以在Component(里面设置要注册成为哪个type)

**Comment by yus1977** [comment]
这个我知道，能不能自动来做。
之前的项目，不同生命周期用了不同属性来标记，用的是Autofac自动扫描注册。
想使用 Autofac.Annotation 又不想动已有的代码，只是把标记的属性修改一下。
因此就有这个问题。

**Comment by yuzd** [comment]
我瞅瞅

**Comment by yus1977** [comment]
thanks
我现在是在AutofacAnnotationModule.RegisterComponentServices里加了下的的一句来测试
if (componentServiceModel.Type.IsAbstract) continue;

**Comment by yus1977** [comment]
@yuzd  我修改了一下如下 ，代码，你看是否可以加入
1、AutofacAnnotationModule 增加两个属性，来标记是否自动注册父类和实现的接口
``` c#
        /// <summary>
        /// 自动注册父类，虚类除外,默认为false
        /// </summary>
        public bool AutoRegisterParentClass { get; set; } = false;
        /// <summary>
        /// 自动按实现的接口注册，默认为false
        /// </summary>
        public bool AutoRegisterInterface { get; set; } = false;
```

2、修改方法 EnumerateComponentServices，在解析时判断是否自动解析父类或接口
``` c#
  ........
            if (bean.Service == null)
            {
                //接口自动注册 父类自动注册
                var typeInterfaces = currentType.GetParentTypes();
                foreach (var iInterface in typeInterfaces)
                {
                    //忽略纯虚类,不自动注册父类和接口
                    if (iInterface.IsAbstract 
                        ||  (iInterface.IsInterface && !AutoRegisterInterface) 
                        || (iInterface.IsClass && !AutoRegisterParentClass))
                        continue;
                    
                      .........
                }
            }

......
```

**Comment by yuzd** [comment]
好的我看下

**Comment by yuzd** [comment]
提交新版到nuget了

由于参考了spring ioc ，它是默认自动注册父类 接口 抽象父类的 所以 你需要按照下面的代码去设置下 关闭这些

```
new AutofacAnnotationModule()
                .SetAutoRegisterInterface(false)
                .SetAutoRegisterParentClass(false)
                .SetIgnoreAutoRegisterAbstractClass(true)
```

**Comment by yus1977** [comment]
多谢！！！



---原始邮件---
发件人: "nainaigu"<notifications@github.com&gt;
发送时间: 2020年8月9日(周日) 下午4:54
收件人: "yuzd/Autofac.Annotation"<Autofac.Annotation@noreply.github.com&gt;;
抄送: "yus"<yus1977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yuzd/Autofac.Annotation] [Component]如果关闭自动注册父类的问题 (#11)




 
提交新版到nuget了
 
由于参考了spring ioc ，它是默认自动注册父类 接口 抽象父类的 所以 你需要按照下面的代码去设置下 关闭这些
 new AutofacAnnotationModule()                 .SetAutoRegisterInterface(false)                 .SetAutoRegisterParentClass(false)                 .SetIgnoreAutoRegisterAbstractClass(true)
