### ISSUE TITLE
泛型类怎么注入

### ISSUE THREAD

**Issue by z514987467** [yuzd/Autofac.Annotation#13]
我试了没了注入不进去，能麻烦写个例子吗

**Comment by z514987467** [comment]
测试已经注入进去了，只是解析的时候出错了，得声明接口才行

**Comment by yuzd** [comment]
你给个出错的例子

**Comment by z514987467** [comment]
`
//泛型接口
public interface IMongodbHelp<T> where T : class { }

//泛型方法实现
[Component(typeof(IMongodbHelp<>))]
public class MongodbHelp<T> : IMongodbHelp<T> where T : class {  }

//注入
builder.RegisterModule(new AutofacAnnotationModule(typeof(MongodbHelp<>).Assembly));
`
报 The type 'Autofac.Configuration.Test.test2.MongodbHelp`1[T]' is not assignable to service 'Autofac.Configuration.Test.test2.IMongodbHelp`1'.的错误
不清楚是不是我写的问题

**Comment by yuzd** [comment]
我研究下

**Comment by z514987467** [comment]
好的，多谢技术分享
