### ISSUE TITLE
添加一个开源协议。

### ISSUE THREAD

**Issue by JasonGrass** [yuzd/Autofac.Annotation#15]
大佬，项目没有开源协议，强烈建议添加一个。
不然不知道该怎么引用。

**Comment by yuzd** [comment]
加了 MIT 
enjoy

**Comment by yuzd** [comment]
还有感谢提价的pr。
不过我想和你讨论下 针对扩展注册这块。我也是打算按照Spring的设计 ，类似的实现一个 BeanFactoryPostProcesser 可以来修改已注册的or新增注册  或者你有啥更好的想法
