### ISSUE TITLE
如何实现对IServiceProvider的属性注入直接贴[Autowired]在基类上貌似无效

### ISSUE THREAD

**Issue by xuejmnet** [yuzd/Autofac.Annotation#17]
![image](https://user-images.githubusercontent.com/18061232/98791157-9833c000-243f-11eb-97ad-ead9f4c9b47a.png)

**Comment by yuzd** [comment]
Autowired 的原理是 当你的类从di容器获取的时候 会扫描从DI容器里面拿到并注入属性。
你没有拿到IserviceProvider 是因为DI容器里面没有注册这个东西。

如果你是aspnetcore应用的话，当你用autofac的话，应该是拿autofac的容器
可以参考

https://github.com/yuzd/AntMgr/blob/master/ant.mgr/mgr.core/Startup.cs#L99
