### ISSUE TITLE
拦截器最新版是去掉了吗

### ISSUE THREAD

**Issue by z514987467** [yuzd/Autofac.Annotation#18]
Aspect拦截器，AspectBeforeAttribute、AspectAfterAttribute找不到了

**Comment by yuzd** [comment]
hi aspect拦截器 有优化 请查看下 wiki  https://github.com/yuzd/Autofac.Annotation/wiki/4.Aspect%E6%8B%A6%E6%88%AA%E5%99%A8
有问题联系我
