### ISSUE TITLE
Debug模式下，动态程序集会导致异常

### ISSUE THREAD

**Issue by yus1977** [yuzd/Autofac.Annotation#19]
项目是一个RazorPage项目，在Debug模式下会出现异常
`     autofac The invoked member is not supported in a dynamic assembly`
Release模式就不会。

调试后发现，是AutofacAnnotationModule里的几个方法中，下面的这行代码导致异常：
`var types = assembly.GetExportedTypes();`
当程序集集合中有动态程序集时会产生异常，这个动态程序集应该是使用dynamic时自动增加的，名字为
`Anonymously Hosted DynamicMethods Assembly `

在上面的代码前面加上动态程序集的判断后，异常就没有了，代码如下：
`if (assembly.IsDynamic) continue;`

**Comment by yuzd** [comment]
感谢 我修复下 或者你会提pr的话，也可以记录你做出的贡献

**Comment by yuzd** [comment]
已发布新版本
