### ISSUE TITLE
[问题]在asp.net mvc 中，Aspect不起作用。

### ISSUE THREAD

**Issue by Cloud33** [yuzd/Autofac.Annotation#2]
已经在 class 打上了标签：
![image](https://user-images.githubusercontent.com/8787198/66476968-8871db80-eac9-11e9-948e-f2cc578a3325.png)

在程序的入口 ，已注入相关的程序集。
`builder.RegisterModule(new AutofacAnnotationModule(typeof(MvcApplication).Assembly));`

但是自定义的Interceptor不进去

最有可能的原因是什么？

**Comment by Cloud33** [comment]
找到原因了，需要使用容器！获取API调用。

**Comment by yuzd** [comment]
是的！
