### ISSUE TITLE
并行注入多个builder.RegisterModule,  Autowired标注使用的地方会出现null的情况

### ISSUE THREAD

**Issue by lounai-chen** [yuzd/Autofac.Annotation#20]
并行注入多个builder.RegisterModule, Autowired使用的地方会出现null的情况
是因为autofac加载Load了多次,导致属性注入DoAutoWired方法执行不成功,componentModelCacheSingleton.ComponentModelCache没有包含实例.

` public void ConfigureContainer(ContainerBuilder builder)
        {
            // Autofac.Annotation 注入 
            builder.RegisterModule(new AutofacAnnotationModule(typeof(TestInterface123).Assembly));

            builder.RegisterModule(new AutofacAnnotationModule(typeof(AabcTestInterface123).Assembly));

            // Autowired 标注的属性注入
            var ControllerBaseType = typeof(ControllerBase);
            builder.RegisterAssemblyTypes(typeof(Program).Assembly)
              .Where(t => ControllerBaseType.IsAssignableFrom(t) && t != ControllerBaseType)
              .PropertiesAutowired(new AutowiredPropertySelector());

        }`

![image](https://user-images.githubusercontent.com/17486997/104977864-8d973780-5a3b-11eb-9b21-aa8b266725b9.png)

**Comment by yuzd** [comment]
好问题，这个场景确实我没有考虑到 可能代码没有适配这种场景 我研究下。

**Comment by yuzd** [comment]
我考虑了很久 决定先不考虑你这种场景，
一个assembly一个配置先不给与支持
