### ISSUE TITLE
两个模块循环引用报错

### ISSUE THREAD

**Issue by lounai-chen** [yuzd/Autofac.Annotation#21]
有设置循环引用,但调试时依然报错 .
` foreach (IConfigurationSection item in config.GetChildren())
            {
                string assemblyName = item.GetSection("name").Value;
                var assembly = Assembly.LoadFile(AppContext.BaseDirectory + @"\" + assemblyName + ".dll");
                assemblyList.Add(assembly);
            }

            var autofacAnnoMe = new AutofacAnnotationModule(assemblyList.ToArray());
            autofacAnnoMe.SetAllowCircularDependencies(true); //允许循环引用
            builder.RegisterModule(autofacAnnoMe);
`
定义类时,加上属性 InjectPropertyType = InjectPropertyType.ALL 可解决此问题. 但是所有接口又都全部自动装配了.
` [Component(AutofacScope= AutofacScope.SingleInstance,InjectPropertyType = InjectPropertyType.ALL )]`

**Comment by yuzd** [comment]
Wo kan kan

**Comment by yuzd** [comment]
有demo么？我没复现

**Comment by yuzd** [comment]
已线下沟通解决
