### ISSUE TITLE
Value标签的值能从nacos里面获取吗？

### ISSUE THREAD

**Issue by z514987467** [yuzd/Autofac.Annotation#22]
Value标签的值能从nacos里面获取吗？

**Comment by yuzd** [comment]
我优化下PropertySource(数据源)
支持可以添加nacos等动态数据源

具体测试例子可以查看：

https://github.com/yuzd/Autofac.Annotation/blob/cbe54de833d698ca28419c51764ed8a4c73e9b92/test/test8/UnitTest8.cs#L26-L66

对应我测试用例的nacos配置:

![image](https://user-images.githubusercontent.com/16083659/115962638-f3b9bc00-a54e-11eb-8cb0-4be22601c829.png)

![image](https://user-images.githubusercontent.com/16083659/115962644-f7e5d980-a54e-11eb-92ad-51ddbcbeed33.png)

**Comment by yuzd** [comment]
这里补充说明下：

像nacos这种动态类型，使用到Property里面dynamic的属性（一个classtype）和key属性
这里要注意这个dynamic的classtype是下面代码中

 builder.RegisterInstance(configurationProvider).Keyed<IConfigurationProvider>("nacos").SingleInstance(); 
 里面注册进去的

所以 [PropertySource(Dynamic = typeof(IConfigurationProvider),Key = "nacos")] 
就代表的是我从容器中根据Key="nacos" 类型是继承IConfigurationProvider获取实例，就是我们上面的注册代码注册的实例

**Comment by z514987467** [comment]
我在Startup类里面注册了
```
public void ConfigureContainer(ContainerBuilder builder)
        {
            builder.RegisterModule(new AutofacAnnotationModule());

            NacosV2ConfigurationSource nacosConfig = Configuration.GetSection("NacosConfig").Get<NacosV2ConfigurationSource>();
            var configurationProvider = nacosConfig.Build(null);
            builder.RegisterInstance(configurationProvider).Keyed<IConfigurationProvider>("nacos").SingleInstance();
        }
```
配置文件如下
```
"NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "statistics.json",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Tenant": "04d48458-908e-4830-b0c6-5ea6f0b69d36",
    "ServerAddresses": [ "http://172.16.12.235:8848/" ],
    "ConfigUseRpc": true
  }
```
还是不行
