### ISSUE TITLE
Pointcut排除namespace 正则表达式如何写

### ISSUE THREAD

**Issue by chenzongxi** [yuzd/Autofac.Annotation#26]
PointCut，
两个命名空间
命名空间A.B.Command.D.Controller下有很多Controller类
命名空间A.B.Config.Controller下有很多Controller类
对A.B.Command.D.Controller进行AOP，排除A.B.Config.Controller。
PointCut怎么写
[Pointcut(NameSpace = "%[^m]%", Class = "*Controller")]
[Pointcut(NameSpace = "A.B.Co[^m]%", Class = "*Controller")]
均不起作用

**Comment by yuzd** [comment]
我看看

**Comment by chenzongxi** [comment]
谢谢

**Comment by yuzd** [comment]
发布了 [4.1.2](https://www.nuget.org/packages/Autofac.Annotation/4.1.2)
你测试看看
