### ISSUE TITLE
如何给方法加注释，AOP中获取注释

### ISSUE THREAD

**Issue by chenzongxi** [yuzd/Autofac.Annotation#27]
AOP中[After(Returing = "value")]获取执行结果，想要记录此方法的可理解的中文日志。
感觉在方法上加特性注解，写上中文注释，AOP中获取特性注解中的中文注释，就可以方便进行日志记录了。

**Comment by yuzd** [comment]
你的意思是 你的方法上有自己的注解，然后希望在AOP方法里面很方面去拿到？

**Comment by chenzongxi** [comment]
我是想通过在方法上添加特性注解，比如[xxx="测试日志"]，然后AOP中获取这个xxx注解，内容就是日志内容，直接保存日志就可以了，日志信息不侵入代码。
不知道Autofac有这样的特性吗？

**Comment by yuzd** [comment]
在Arround里面是可以拿到被代理的Method
然后可以拿到method的Attribute
你看这样行哇

**Comment by chenzongxi** [comment]
好的，谢谢。有没有更好的实现中文日志的思路？

**Comment by yuzd** [comment]
我觉得就按照你说的就ok
首先自定义一个Attribute，然后你打在方法上面
在pointcut中拿到它来记录
