### ISSUE TITLE
IOC注入，可以在构造函数中使用吗

### ISSUE THREAD

**Issue by chenzongxi** [yuzd/Autofac.Annotation#28]
public class A
    {
        [Autowired]
        public B b{ get; set; }
        private C c;

        public A()
        {
            this.c = b.c;
        }
    }

A构造函数中不能使用b，b还没注入，是null。
如何实现构造函数中访问注入的对象

**Comment by yuzd** [comment]
试试这样：


public class A
{

public B b{ get; set; }
private C c;

    public A( B b)
    {
    this.b = b;
        this.c = b.c;
    }
}

**Comment by chenzongxi** [comment]
试了，可以的，谢谢。以下两种也可以
public class A
{
private C c;

public A( B b)
{
    this.c = b.c;
}
}

public class A
{
private C c;

public A([Autowired] B b)
{
    this.c = b.c;
}
}

**Comment by chenzongxi** [comment]
构造函数注入和属性注入区别

**Comment by yuzd** [comment]
构造函数注入的 如果遇到循环注入会报错
但是属性注入就不会

**Comment by chenzongxi** [comment]
谢谢
