### ISSUE TITLE
[Pointcut(AttributeType = typeof(LogAttribute))]不起作用

### ISSUE THREAD

**Issue by tianmafly** [yuzd/Autofac.Annotation#30]
[AttributeUsage(AttributeTargets.All,  AllowMultiple = true)]
    public class LogAttribute : Attribute
    {
        public string message { get; set; }
        public string actionName { get; set; }

        public LogAttribute(string message, string actionName)
        {
            this.message = message;
            this.actionName = actionName;
        }
    }

//[Pointcut(Class = "[^Api]*Controller")]
[Pointcut(AttributeType = typeof(LogAttribute))]
    public class LogInterceptor : IInterceptor
    {
        [Around]
        public async Task Around(AspectContext context, AspectDelegate next)
        {
            //没有执行
        }
    }

[LogAttribute("", "")]
        public virtual void CheckCommand(byte[] cmd)
        {
            //执行此方法，没有进入AOP的Around
        }

AOP类没问题，因为[Pointcut(Class = "[^Api]*Controller")]可以对Controller类进行Around操作，换成[Pointcut(AttributeType = typeof(LogAttribute))]，就不会对LogAttribute注解类进行Around操作。
哪里写的不对吗？

**Comment by tianmafly** [comment]
https://github.com/yuzd/Autofac.Annotation/issues/31#issue-1429221648
应该是同一个问题，可能因为继承接口导致的。

**Comment by yuzd** [comment]
升级到最新版本后你在验证下看看

**Comment by tianmafly** [comment]
https://github.com/yuzd/Autofac.Annotation/issues/31#issuecomment-1297962662
这是bug？
