### ISSUE TITLE
子类继承父类，AOP不起作用

### ISSUE THREAD

**Issue by tianmafly** [yuzd/Autofac.Annotation#31]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/38370307/198929490-5ae71ca0-f223-4cf9-800b-c96e01d7d43a.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/38370307/198929535-8ed1fd88-ac33-4c0d-9406-c1b2dc1082f8.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/38370307/198929810-921e3a6e-db00-4e89-8223-f81a51b02eca.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/38370307/198929718-af153ff9-8ee1-4d91-9f2c-10229a5f4109.png">

**Comment by tianmafly** [comment]
[Autowired("test1")]要写哪个名字，这里不能进入LogInterceptor。
如果Test1不继承接口ICommunication，则可以进入LogInterceptor

**Comment by yuzd** [comment]
等会看下

**Comment by tianmafly** [comment]
如果把接口ICommunication改成类，就没问题了Test1继承类ICommunication，就没问题了。具体如何改？

**Comment by tianmafly** [comment]
接口改成类后，AOP用class=""方式可以，但AttributeType方式有问题：

<img width="340" alt="image" src="https://user-images.githubusercontent.com/38370307/198956988-73f1726b-569d-46a2-84d2-53ae597151aa.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/38370307/198957023-621f5a13-415b-4db1-9ca5-02903772e35d.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/38370307/198957335-ab14aee0-8927-4edf-b47d-5842312ab5e6.png">

**Comment by yuzd** [comment]
稍等 我还原下这个问题

**Comment by yuzd** [comment]
请更新nuget到4.1.4版本

你列举的2点针对的修复后的单元测试请参考：

https://github.com/yuzd/Autofac.Annotation/blob/master/test/issue31/TestInheritedAop.cs

**Comment by yuzd** [comment]
要注意一点，如果你要pointcut Mvc的Controller 
如果不希望拦截父类的 可以显示关闭
![image](https://dimg04.c-ctrip.com/images/0v52w12000a4khzmw4999.png)

**Comment by tianmafly** [comment]
继承接口没问题了。
ExceptionAttribute放接口上不起作用，需要放到实现类方法上才起作用，而放抽象类上可以。
最好放到接口上，否则多个实现类都要在方法上放ExceptionAttribute

**Comment by tianmafly** [comment]
ICommunication没有CheckCommand，实现类有CheckCommand方法，方法内部调用，CheckCommand方法不会进入AOP。
这也不太对吧
![image](https://user-images.githubusercontent.com/38370307/199155692-461ac48a-838a-4583-85df-1efd519ed091.png)

**Comment by yuzd** [comment]
ExceptionAttribute放接口类和接口方法上不起作用
这个我看看

**Comment by yuzd** [comment]
> ICommunication没有CheckCommand，实现类有CheckCommand方法，方法内部调用，CheckCommand方法不会进入AOP。 这也不太对吧 ![image](https://user-images.githubusercontent.com/38370307/199155692-461ac48a-838a-4583-85df-1efd519ed091.png)

方法内部调用非aop代理对象，所以不会走到aop
这个是aop的一个注意点，必须得用目标的代理类对象去调用

**Comment by yuzd** [comment]
ExceptionAttribute放接口类和接口方法上不起作用 
虽然你设置了Attribute可以传递 但是打在接口的方法上 
到了class这层还是拿不到的，
下面这个链接说明了为什么微软这么设计，可以看一下
https://stackoverflow.com/questions/12106566/attribute-on-interface-members-does-not-work

**Comment by yuzd** [comment]
更新4.1.5试试 已修复ExceptionAttribute放接口类和接口方法上不起作用的问题了
另外 请注意看我新添加的单元测试，如果是接口类型的话 需要指定
![image](https://dimg04.c-ctrip.com/images/0v53712000a4lmkv66A21.png)

如果是非接口类型的话 是需要指定virtual （默认Attribute方式aop是这种，所以上面你用接口的方式得注意）
![image](https://dimg04.c-ctrip.com/images/0v51z12000a4lmr61BB20.png)



具体看我新添加的单元测试把
https://github.com/yuzd/Autofac.Annotation/blob/master/test/issue31/TestInheritedAop.cs

**Comment by tianmafly** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/38370307/199606675-6d22549e-2d8e-474a-9d58-0798d52433be.png">
方法内部调用非aop代理对象，所以不会走到aop
这个是aop的一个注意点，必须得用目标的代理类对象去调用
public virtual void Send(byte[] data)可以进aop
public virtual void CheckCommand(byte[] cmd)不可以进
Test1被aop代理了，CheckCommand必须test1.CheckCommand()直接调用？内部方法间接调用不可以？

**Comment by tianmafly** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/38370307/199607976-78eaf394-806a-4d8b-b256-5d6bf0611141.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/38370307/199608086-285a9499-b743-4e01-b5ff-28019a76e6ef.png">

ICommunication改成抽象类，CheckCommand是抽象类方法，
Send，CheckCommand都可以进aop，CheckCommand是方法内部调用

**Comment by tianmafly** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/38370307/199611892-5811530d-b5c7-46b0-9172-c2eac636b087.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/38370307/199611932-eeea30a3-792d-41fd-8720-48c9f7d4fe06.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/38370307/199612054-e37e3570-3a48-4ee4-96c6-c910e7858e49.png">
没有进入aop

**Comment by yuzd** [comment]
> <img alt="image" width="659" src="https://user-images.githubusercontent.com/38370307/199606675-6d22549e-2d8e-474a-9d58-0798d52433be.png">
> 
> 方法内部调用非aop代理对象，所以不会走到aop 这个是aop的一个注意点，必须得用目标的代理类对象去调用
> public virtual void Send(byte[] data)可以进aop public virtual void CheckCommand(byte[] cmd)不可以进 Test1被aop代理了，CheckCommand必须test1.CheckCommand()直接调用？内部方法间接调用不可以？

你这种是不行的，因为你在 Send里面调用内部方法CheckCommand相当于是this。这个this不是代理对象

**Comment by yuzd** [comment]
你可以把当前当前对象注入进来
```csharp
[Autowired("test1")]
public Icomminucation1 Test1
```

然后在Send方法里面把 CheckCommand 改成 Test1.CheckCommand

**Comment by tianmafly** [comment]
> <img alt="image" width="654" src="https://user-images.githubusercontent.com/38370307/199607976-78eaf394-806a-4d8b-b256-5d6bf0611141.png">
> 
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/38370307/199608086-285a9499-b743-4e01-b5ff-28019a76e6ef.png">
> 
> ICommunication改成抽象类，CheckCommand是抽象类方法， Send，CheckCommand都可以进aop，CheckCommand是方法内部调用

那这种父类的，CheckCommand相当于base.CheckCommand()？

**Comment by yuzd** [comment]
> <img alt="image" width="654" src="https://user-images.githubusercontent.com/38370307/199607976-78eaf394-806a-4d8b-b256-5d6bf0611141.png">
> 
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/38370307/199608086-285a9499-b743-4e01-b5ff-28019a76e6ef.png">
> 
> ICommunication改成抽象类，CheckCommand是抽象类方法， Send，CheckCommand都可以进aop，CheckCommand是方法内部调用

你试过 不由方法内部调用 直接调用CheckCommand可以进AOP吗

**Comment by tianmafly** [comment]
1. 不由方法内部调用 子类直接调用CheckCommand可以进AOP，加virtual
2. 调用父类方法，加上base.不进入aop。不加base.可以进入aop，且父类方法可proteced

**Comment by tianmafly** [comment]
![image](https://user-images.githubusercontent.com/38370307/199629294-dd685996-d3f8-439b-8f45-c7334fe4e043.png)
![image](https://user-images.githubusercontent.com/38370307/199629315-60f6411f-7bff-4f90-8695-cbabb371124b.png)
![image](https://user-images.githubusercontent.com/38370307/199629359-b4a96f6d-2173-42d7-822e-bc1719967d4c.png)

现在是以下两个方法加this，不加this都可以进入aop，
this.CheckCommand(data);
this.CheckCommand1(data);

但如果base.CheckCommand(data);不可以进入。
感觉和之前测试不太一样。有点混乱了

**Comment by tianmafly** [comment]
> ![image](https://user-images.githubusercontent.com/38370307/199629294-dd685996-d3f8-439b-8f45-c7334fe4e043.png) ![image](https://user-images.githubusercontent.com/38370307/199629315-60f6411f-7bff-4f90-8695-cbabb371124b.png) ![image](https://user-images.githubusercontent.com/38370307/199629359-b4a96f6d-2173-42d7-822e-bc1719967d4c.png)
> 
> 现在是以下两个方法加this，不加this都可以进入aop， this.CheckCommand(data); this.CheckCommand1(data);
> 
> 但如果base.CheckCommand(data);不可以进入。

**Comment by yuzd** [comment]
是class +virtual类型的是吧

**Comment by yuzd** [comment]
加this可以，加base不可以，this指向代理类，所以可以，base没有代理类所以不可以？
-> 理解正确

**Comment by yuzd** [comment]
我发现了一个新问题
循环注入自己，居然拿的不是代理类
![image](https://dimg04.c-ctrip.com/images/0v51d12000a4rma0g6EDD.png)

**Comment by yuzd** [comment]
> 我发现了一个新问题 循环注入自己，居然拿的不是代理类 ![image](https://camo.githubusercontent.com/4125db0ffec604763208838afb32e156017125610bfff850430c9210962ad734/68747470733a2f2f64696d6730342e632d63747269702e636f6d2f696d616765732f307635316431323030306134726d613067364544442e706e67)

4.1.7版本修复了

**Comment by yuzd** [comment]
```csharp

[Component("test7")]
[InterfaceInterceptor]
public class Test7 : ICommunication6
{
    // 这里为啥非代理类
    [Autowired("test7", CircularDependencies = true)]
    public ICommunication6 _test7;

    public void Send(string data)
    {
        ApiPationInfoController.result12.Add("data1");
        _test7.Send2(data);
    }

    public void Send2(string data)
    {
        ApiPationInfoController.result12.Add("data2");
    }
}


```

**Comment by yuzd** [comment]
请更新到4.1.8版本
不需要指定是否开启支持循环依赖注入
默认就开启，去掉了要手动开启的开关配置了

**Comment by tianmafly** [comment]
nuget没有4.1.8


> <img alt="image" width="268" src="https://user-images.githubusercontent.com/38370307/199611892-5811530d-b5c7-46b0-9172-c2eac636b087.png">
> 
> <img alt="image" width="452" src="https://user-images.githubusercontent.com/38370307/199611932-eeea30a3-792d-41fd-8720-48c9f7d4fe06.png">
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/38370307/199612054-e37e3570-3a48-4ee4-96c6-c910e7858e49.png">
> 
> 没有进入aop。4.1.5，4.1.6都试了试 写的应该和你的测试用例一样

这个解决了吗

**Comment by yuzd** [comment]
> ```cs
> [Component("test7")]
> [InterfaceInterceptor]
> public class Test7 : ICommunication6
> {
>     // 引入自身
>     [Autowired("test7")]
>     public ICommunication6 _test7;
> 
>     public void Send(string data)
>     {
>         ApiPationInfoController.result12.Add("data1");
>        //内部调用也可以走AOP
>         _test7.Send2(data);
>     }
> 
>     public void Send2(string data)
>     {
>         ApiPationInfoController.result12.Add("data2");
>     }
> }
> ```

看这个，只有这样才能解决

**Comment by yuzd** [comment]
等等 马上就有4.1.8了

**Comment by tianmafly** [comment]
那就是AOP中class=，可以直接用接口。ExceptionAttribute=，需要引入自身才能用接口？

**Comment by yuzd** [comment]
只有内部掉内部需要显示使用，其他情况不需要

**Comment by tianmafly** [comment]
> nuget没有4.1.8
> 
> > <img alt="image" width="268" src="https://user-images.githubusercontent.com/38370307/199611892-5811530d-b5c7-46b0-9172-c2eac636b087.png">
> > <img alt="image" width="452" src="https://user-images.githubusercontent.com/38370307/199611932-eeea30a3-792d-41fd-8720-48c9f7d4fe06.png">
> > <img alt="image" width="554" src="https://user-images.githubusercontent.com/38370307/199612054-e37e3570-3a48-4ee4-96c6-c910e7858e49.png">
> > 没有进入aop。4.1.5，4.1.6都试了试 写的应该和你的测试用例一样
> 
> 这个解决了吗

这是直接调用，我这不进aop

**Comment by yuzd** [comment]
你的 ExceptionAttribute是继承了下面这些吗
![image](https://dimg04.c-ctrip.com/images/0v54612000a4skrp1287E.png)

**Comment by yuzd** [comment]
你的这种方式 Send是肯定得走AOP的

**Comment by yuzd** [comment]
加QQ 1877682825 沟通快点

**Comment by tianmafly** [comment]
加了
