### ISSUE TITLE
在asp.net core框架下使用[PropertySource(Dynamic = typeof(IConfigurationProvider))]无效

### ISSUE THREAD

**Issue by z514987467** [yuzd/Autofac.Annotation#34]
1. 通过注入IConfiguration看到有6个实现
![image](https://user-images.githubusercontent.com/27339094/211751590-593e034d-b0f1-4cc9-b05f-002a7946063d.png)

2. 通过Value无法获取到值
![1673424483868](https://user-images.githubusercontent.com/27339094/211751839-5648ecb9-eea2-49da-92e8-04712fd65586.png)

请教下，是我用的不对吗？

**Comment by yuzd** [comment]
如果你是用的是本地json文件的配置的话
去掉Property里面的dynamic不用设置（你去掉试试），dynamic这个是用来设置比如像nacos这样动态的扩展的，
可以参考https://github.com/yuzd/Autofac.Annotation/issues/22

**Comment by yuzd** [comment]
参考 https://github.com/yuzd/Autofac.Annotation/issues/22 我加了补充说明
如果你是nacos的话，得注意一下你得把nacos的实例给注册进去才行

**Comment by z514987467** [comment]
使用的是nacos，用本地的appsettings.json可以

**Comment by yuzd** [comment]
[PropertySource(Dynamic = typeof(IConfigurationProvider),Key = "nacos")]
 你换成这样试试呢

**Comment by z514987467** [comment]
一样效果的

**Comment by yuzd** [comment]
代码异常明细有吗
比如堆栈

**Comment by z514987467** [comment]
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=Value set error,can not resolve class type:Air.Statistics.Test =====> String ,with value:[${a}]
  Source=Autofac.Annotation
  StackTrace:
   在 Autofac.Annotation.Value.Resolve(IComponentContext context, Type classType, Type memberType, String parameterInfo, AutoConfigurationDetail autoConfigurationDetail)
   在 Autofac.Annotation.ObjectBeanFactory.<>c__DisplayClass3_0.<CreateValueFactory>g__Function|0()
   在 Autofac.Annotation.ValueObjectFactory`1.get_Value()
   在 Air.Statistics.Test.M1() 在 E:\Workspace\AirBusiness\Data_Learning\Air.Statistics\Test.cs 中: 第 23 行
   在 Air.Statistics.Controllers.StatisticsController.Test() 在 E:\Workspace\AirBusiness\Data_Learning\Air.Statistics\Controllers\StatisticsController.cs 中: 第 70 行
   在 Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   在 Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   在 Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
Exception: Could not resolve placeholder 'a'.

**Comment by yuzd** [comment]
你先测试下 用 https://github.com/nacos-group/nacos-sdk-csharp
手动写代码 看能否读取到？
这是为了排除nacos环境问题

**Comment by z514987467** [comment]
我通过注入IConfiguration获取能获取到
![image](https://user-images.githubusercontent.com/27339094/211994727-ec365ca8-523d-4dd4-85fd-0722493fb309.png)

**Comment by yuzd** [comment]
按照你的写法
拿到的是本地appsettings.json里面的呀

**Comment by yuzd** [comment]
> Autofac.Core.DependencyResolutionException HResult=0x80131500 Message=Value set error,can not resolve class type:Air.Statistics.Test =====> String ,with value:[${a}] Source=Autofac.Annotation StackTrace: 在 Autofac.Annotation.Value.Resolve(IComponentContext context, Type classType, Type memberType, String parameterInfo, AutoConfigurationDetail autoConfigurationDetail) 在 Autofac.Annotation.ObjectBeanFactory.<>c__DisplayClass3_0.g__Function|0() 在 Autofac.Annotation.ValueObjectFactory`1.get_Value() 在 Air.Statistics.Test.M1() 在 E:\Workspace\AirBusiness\Data_Learning\Air.Statistics\Test.cs 中: 第 23 行 在 Air.Statistics.Controllers.StatisticsController.Test() 在 E:\Workspace\AirBusiness\Data_Learning\Air.Statistics\Controllers\StatisticsController.cs 中: 第 70 行 在 Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters) 在 Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) 在 Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<g__Logged|12_1>d.MoveNext()
> 
> 此异常最初是在此调用堆栈中引发的: [外部代码]
> 
> 内部异常 1: Exception: Could not resolve placeholder 'a'.

你配置的propertysource是nacos的话，如果从nacos拿不到的话 就会报这个错误

**Comment by z514987467** [comment]
nacos上配置的，我看IConfiguration有7个实现
![image](https://user-images.githubusercontent.com/27339094/211998353-9c601f3e-b9bf-4818-ac76-0afc41af3b19.png)
1. 如果appsettings.json和nacos都配置了，会以nacos配置的值
2. 如果appsettings.json和nacos配置一个，也会拿到值

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/212001324-7d8a75e0-c99c-4532-9863-10c7193acc4d.png)

估计你是配置了这个

**Comment by z514987467** [comment]
我升级下nacos-sdk版本再试试

**Comment by yuzd** [comment]
你配置了这个 所有IConfiguration 里面有Nacos

所有你根据configuration拿是可以拿到的

如果用Value标签的话，他的原理是根据你从你配置的PropertySource调用

Configuration.GetSection("xxx") 来获取

如果你不配置PropertySource 默认会从项目的appsettings.json里面拿，如果你配置Source是Dynamic 【nacos】
它就会调用nacos的configuration 调用 GetSection去获取

我觉得应该不是nacos版本的问题

要排查下是不是 调用GetSection方法获取不到

**Comment by yuzd** [comment]
加我qq 1877682825

**Comment by yuzd** [comment]
nacos版本
![image](https://dimg04.c-ctrip.com/images/0v52q12000afhwnw7436B.png)

nacoscsharp客户端版本
1.3.4

需要调整下注册nacos类型PropertySource的方式 如下代码

https://github.com/yuzd/Autofac.Annotation/blob/d8dd898b27dcd8b638b4be77efc412cbab3bb060/nacosTest/Program.cs#L8-L34

也可以查看gitclone 后查看
![image](https://dimg04.c-ctrip.com/images/0v54p12000afhwz7p6D6A.png)

我测试配置是用docker搭建的standalone环境

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "jsontest",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Namespace": "fb371f5e-78ac-45bf-aadf-076d61b865c2",
    "ServerAddresses": [
      "http://127.0.0.1:8848/"
    ],
    "UserName": "nacos",
    "Password": "nacos",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": "acm.aliyun.com"
  }
}

```
