### ISSUE TITLE
Question about internal classes with [Component] annotation

### ISSUE THREAD

**Issue by reza-repo** [yuzd/Autofac.Annotation#35]
From my limited testing, internal classes (with a public constructor) do not get registered. Is there a setting or property that I may be missing?

```c#
[Component]
internal class IntReader
{
    public int ReadInt()
    {
        return new Random().Next();
    }
}
```

**Comment by yuzd** [comment]
wait a minute, let me see

**Comment by yuzd** [comment]
```csharp
assembly.GetExportedTypes()

⇓

assembly.GetTypes()
```
nuget version : 4.3.9
try again

**Comment by yuzd** [comment]
Ok，Feel free to contact me with any questions
