### ISSUE TITLE
asp.netcore7 razar pages中无法使用

### ISSUE THREAD

**Issue by brucexhe** [yuzd/Autofac.Annotation#36]
service使用component,在 pagemodel中使用autowired无法获取得实例

**Comment by yuzd** [comment]
有相关代码可以帮助我复现？

**Comment by brucexhe** [comment]
大佬你好，我用的是asp.netcore7中的 razar page，即页面是继承PageModel的，我看到了你的program.cs上用了这一句：
// 设置Controller实例的生成也交给autofac
//builder.Host.ConfigureServices(services => { services.Replace(ServiceDescriptor.Transient<IControllerActivator, ServiceBasedControllerActivator>()); });

于是我替换成了如下：
builder.Host.ConfigureServices(services => { services.Replace(ServiceDescriptor.Transient<IPageModelActivatorProvider, ServiceBasedPageModelActivatorProvider>()); });

现在能够正常工作了，但是必须加上 [Component]才行，即：
    [Component]
    public class LoginModel : PageModel
    {     }

也就是说我必须在所有的pagemodel class上加上[Component] （你之前的controller模式也一样），我感觉这里是不是和上面的builder.Host.ConfigureServices(xxxx  有点冗余 ？

**Comment by yuzd** [comment]
参考
https://autofac.readthedocs.io/en/latest/register/scanning.html
把所有继承PageModel的都注入？

**Comment by brucexhe** [comment]
可以的，谢谢！

然后，我想提个小小的建议：

是否 可以 把 替换默认实例生成器的 代码，即：builder.Host.ConfigureServices(services => controller/pagemodel/xxxx等写到插件默认配置里，同时把 controller/pagemodel等 需要加[component]的web控制器 设置为插件默认自动注入。

这样，用户只需要 使用 app.UseAutofacAnnotation() 即可开箱使用， 无需任何配置。

再次感谢你提供这个插件，超过springboot指日可待！

**Comment by yuzd** [comment]
good idea 
这样可以提高体验，
我研究研究
