### ISSUE TITLE
Value的IgnoreUnresolvablePlaceholders=true未起作用

### ISSUE THREAD

**Issue by Decmoe47** [yuzd/Autofac.Annotation#39]
假设有如下的配置：

```json
{
    "abc": "abc"
}
```

然后映射类如下：

```c#
[Component]
public class MyConfig 
{
    [Value("${abc}")]
    public string Abc { get; set; }

    [Value("${test}", IgnoreUnresolvablePlaceholders = true)]
    public int Test { get; set; }
}
```

此时就会报错：

```
Autofac.Core.DependencyResolutionException: An exception was thrown while activating MyProject.MyConfig.
 ---> Autofac.Core.DependencyResolutionException: Value set error,can not resolve class type:MyProject.MyConfig =====> Int32 ,with value:[${test}]
 ---> Spring.Core.TypeMismatchException: Cannot convert property value of type [System.String] to required type [System.Int32] for property ''.
 ---> System.ArgumentException: ${test} is not a valid value for Int32. (Parameter 'value')
 ---> System.FormatException: The input string '${test}' was not in a correct format.
```

其原因是`Value.Resolve()`中的`ResolveSpel()`在找不到值时返回了配置的键名赋给`parameterValue`，

https://github.com/yuzd/Autofac.Annotation/blob/a6f9b8b9197317a554696377aa7bcfb78078b724/src/Anotation/Value.cs#L158-L162

而TypeMismatchException则是在`ConvertValueIfNecessary()`中抛出。

`ResolveSpel()`在找不到值时且`IgnoreUnresolvablePlaceholders=true`返回的是配置项的键名很奇怪。按理说`ResolveSpel()`应该返回个null然后进入161行的`if (parameterValue == null) return null;`处，`Resolve()`最终返回null跳过此配置项。

<br />

以我的理解，在`ResolveEmbeddedValue()`里的第260行处应该返回`null`而不是`strVal`。

https://github.com/yuzd/Autofac.Annotation/blob/a6f9b8b9197317a554696377aa7bcfb78078b724/src/Anotation/Value.cs#L250-L261

然后在`ResolveSpel()`里的第195行前写上if判空提前返回：

https://github.com/yuzd/Autofac.Annotation/blob/a6f9b8b9197317a554696377aa7bcfb78078b724/src/Anotation/Value.cs#L192-L196

```c#
if (parameterValue == null)
    return null;
```

**Comment by yuzd** [comment]
非常到位，赞
能否提个PR，谢谢

**Comment by yuzd** [comment]
到位，已修复

**Comment by Decmoe47** [comment]
不好意思，遗漏了一种情况。

如果`UseSpel = false`然后写不带`${}`的话，仍然会报同样的错。

其原因是，本身值就不存在，于是下面“原生的获取方式”那里就不会返回继续执行后面的代码：

https://github.com/yuzd/Autofac.Annotation/blob/4185c0df07e2ac5ce2bbb26e14c7e9e95b8028a1/src/Anotation/Value.cs#L148-L162

而在`ResolveEmbeddedValue()`中因为找不到`${`所以原样返回键名，就导致了193行的`parameterValue`为非null，后面if没能防御成功。

https://github.com/yuzd/Autofac.Annotation/blob/4185c0df07e2ac5ce2bbb26e14c7e9e95b8028a1/src/Anotation/Value.cs#L248-L249

https://github.com/yuzd/Autofac.Annotation/blob/4185c0df07e2ac5ce2bbb26e14c7e9e95b8028a1/src/Anotation/Value.cs#L193-L198

所以应该在155行后加上：

```c#
else if (IgnoreUnresolvablePlaceholders)
{
    return null;
}
```

另外，按照原来的逻辑，似乎是即使`UseSpel = false`，当原生的方式读取不到值时，也还要尝试去当成spel读一下。但我觉得没有必要，既然`UseSpel = false`了，那还写成spel的话，就是使用者的责任。因此我觉得如果`UseSpel = false, IgnoreUnresolvablePlaceholders = false`又取不到值的话，可以直接抛错。

**Comment by yuzd** [comment]
更新好了 v4.4.5
