### ISSUE TITLE
[问题] 在3.1.2中，PointcutAttribute拦截器去掉了？

### ISSUE THREAD

**Issue by Cloud33** [yuzd/Autofac.Annotation#4]
我使用3.1.2版本，发现已经实现不了PointcutAttribute中的OnInvocation方法了，是不是去掉了？

**Comment by yuzd** [comment]
## 新版本中PointcutAttribute代表是定义一个切面，使用说明可以参考：https://github.com/yuzd/Autofac.Annotation/wiki/5-Pointcut%E5%88%87%E9%9D%A2%E7%BC%96%E7%A8%8B

## 实际在DB的Transaction的使用例子请参考代码：
https://github.com/yuzd/AntMgr/wiki/%E6%9C%AC%E6%A1%86%E6%9E%B6%E4%B8%8B%E7%9A%84%E4%BA%8B%E7%89%A9%E5%88%87%E9%9D%A2%E7%BC%96%E7%A8%8B%E6%8A%80%E6%9C%AF


## 这么改的好处是你可以切n个类的n个方法，不用一个个类里面去配置了。


## 如果你想要新版本中继续沿用之前的在类上面打拦截器标签请换成用 AspectPointAttribute

**Comment by Cloud33** [comment]
明白了，谢谢
