### ISSUE TITLE
pointcut 使用异常问题

### ISSUE THREAD

**Issue by Wisehit** [yuzd/Autofac.Annotation#6]
[Pointcut(Class = "*Controller", Method = "Get*")]

The requested service '***.HomeController' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency
再homecontroller 中添加了getuser 无法正常使用

**Comment by yuzd** [comment]
controller层交给autofac处理了吗？
Aspnetcore版本？

**Comment by Wisehit** [comment]
controller 是托管给autofac 不使用pointcut 能够正常使用，加上了就不能创建homecontroller 对象了

**Comment by yuzd** [comment]
升级到最新版本 3.1.4

![image](https://images4.c-ctrip.com/target/zb0h1h000001ho93o42CB.png)

```csharp
//这行代码代表 controller的实例的创建交给autofac容器处理 
     services.Replace(ServiceDescriptor.Transient<IControllerActivator, ServiceBasedControllerActivator>());
```

```csharp

//除了上面那段代码以外，只能实现autofac去创建controller对象 ，但是必须得打【Compoment】标签注册到autofac容器才行

 [Component]
public class HomeController : ControllerBase
{

}
```
