### ISSUE TITLE
自定义函数执行慢的问题

### ISSUE THREAD

**Issue by wurangbo** [yuzd/Autofac.Annotation#8]
我这边在使用的过程中，发现如果在表达式中使用自定义函数的时候，spring.el是通过创建委托的方式来实现，这个时间比较久，我这边测似乎在0.2S以上，有什么优化的方式

**Comment by wurangbo** [comment]
Spring.Expressions.Parser.antlr.MismatchedCharException 
Spring.Expressions.Parser.antlr.NoViableAltForCharException
我看了日志，提示了以上的錯誤。

**Comment by yuzd** [comment]
有示例代码么
